package service.calculation;

public enum CalculationValue {
    CONTROL_CONDITION_DATE,
    CONTROL_CONDITION_PROTOCOL_NUMBER,
    CONTROL_CONDITION_CALIBRATOR_NAME,
    CONTROL_CONDITION_TEMPERATURE,
    CONTROL_CONDITION_HUMIDITY,
    CONTROL_CONDITION_PRESSURE
}
